[images]
  remote_images = []

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://robbowen-clone.netlify.app"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[dev]
  command = "bun run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
